server:
  port: 9999
  servlet.session.timeout: 600
  
spring:
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/Rn6mm1eIfC?useSSL=false
    username: username
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update